// Единый источник данных раундов — используется и клиентом (app.js), и сервером (server.js).

export const fullRounds = [
  {
    title: "Разминка",
    resource: "Разминка",
    cityName: "Фитнес-спа",
    durationMs: 20000,
    questions: [
      {
        type: "choice",
        prompt: "Что обычно означает сообщение «Работает у меня на компьютере»?",
        options: ["Бага не существует", "Проблема точно у пользователя", "Всё уже исправлено", "Можно выкатывать в прод"],
        correct: "B",
      },
      {
        type: "choice",
        prompt: "Какой статус задачи самый опасный?",
        options: ["Done", "In Progress", "На согласовании", "Почти готово"],
        correct: "D",
        runawayOption: "D",
        runawayDelayMs: 15000,
      },
      {
        type: "choice",
        prompt: "Что происходит сразу после фразы «Быстро поправлю одну строчку»?",
        options: ["Всё работает", "+3 часа работы", "Код становится короче", "Все идут домой"],
        correct: "B",
      },
      {
        type: "choice",
        prompt: "Что чаще всего означает сообщение «Есть маленькая доработка»?",
        options: ["5 минут работы", "Полностью новый функционал", "Нужно изменить цвет кнопки", "Исправить опечатку"],
        correct: "B",
      },
      {
        type: "choice",
        prompt: "Что обычно появляется сразу после релиза?",
        options: ["Отпуск", "Новые баги", "Повышение зарплаты", "Благодарственное письмо"],
        correct: "B",
      },
      {
        type: "choice",
        prompt: "Какой вопрос чаще всего задаёт заказчик?",
        options: ["Когда будет готово?", "Как это работает?", "Какой стек?", "Что такое Docker?"],
        correct: "A",
      },
      {
        type: "choice",
        prompt: "Какой самый страшный звук для айтишника?",
        options: ["Teams звонок", "«Есть минутка?»", "Будильник", "Битрикс уведомление"],
        correct: "B",
      },
    ],
  },
  {
    title: "Цена вопроса",
    resource: "Банк",
    durationMs: 45000,
    questions: [
      {
        type: "choice",
        prompt: "Что дороже?",
        options: ["Видеокарта RTX 4070 Super", "Годовая подписка на облачное хранилище 1 ТБ"],
        correct: "A",
      },
      {
        type: "choice",
        prompt: "Что дороже?",
        options: ["Маникюр с покрытием и дизайном", "Механическая клавиатура", "Примерно одинаково"],
        correct: "C",
      },
      {
        type: "choice",
        prompt: "Что дороже?",
        options: ["Сумка Furla / Michael Kors", "SSD на 2 ТБ"],
        correct: "A",
      },
      {
        type: "choice",
        prompt: "Что дороже?",
        options: ["Аренда ВМ для стандартной работы на год", "Пиджак среднего бренда на мероприятие"],
        correct: "A",
      },
      {
        type: "choice",
        prompt: "Что из этого обычно самое дорогое?",
        options: ["iPhone последней модели", "RTX 4070 Super", "Пиджак среднего бренда", "Годовой абонемент в зал"],
        correct: "A",
      },
      {
        type: "choice",
        prompt: "Что из этого обычно самое дешёвое?",
        options: ["Годовая подписка на онлайн-кинотеатр", "Механическая клавиатура", "Кофе с круассаном", "Маникюр с дизайном"],
        correct: "C",
      },
      {
        type: "choice",
        prompt: "Что дороже?",
        options: ["Ремонт зуба с коронкой", "Замена оперативной памяти в ноутбуке"],
        correct: "A",
      },
    ],
  },
  {
    title: "Угадай фильм",
    resource: "Кинотеатр",
    durationMs: 45000,
    mediaSide: "left",
    answerReview: true,
    questions: [
      { type: "text", image: "assets/film-1-blur.png", revealImage: "assets/film-1-original.png", prompt: "Угадай фильм по заблюренному кадру.", answer: "Отель Гранд Будапешт", answerTitle: "Отель Гранд Будапешт" },
      { type: "text", image: "assets/film-2-blur.png", revealImage: "assets/film-2-original.png", prompt: "Угадай фильм по заблюренному кадру.", answer: "Шоу Трумана", answerTitle: "Шоу Трумана" },
      { type: "text", image: "assets/film-3-blur.png", revealImage: "assets/film-3-original.png", prompt: "Угадай фильм по заблюренному кадру.", answer: "Мой сосед Тоторо", answerTitle: "Мой сосед Тоторо" },
      { type: "text", image: "assets/film-4-blur.png", revealImage: "assets/film-4-original.png", prompt: "Угадай фильм по заблюренному кадру.", answer: "В поисках Немо", answerTitle: "В поисках Немо" },
      { type: "text", image: "assets/film-5-blur.png", revealImage: "assets/film-5-original.png", prompt: "Угадай фильм по заблюренному кадру.", answer: "Касабланка", answerTitle: "Касабланка" },
      { type: "text", image: "assets/film-6-blur.png", revealImage: "assets/film-6-original.png", prompt: "Угадай фильм по заблюренному кадру.", answer: "Космическая одиссея 2001", answerTitle: "Космическая одиссея 2001", acceptedAnswers: ["космическая", "космическая одиссея", "2001 космическая одиссея", "космическая одиссея 2001"] },
      { type: "text", image: "assets/film-7-blur.png", revealImage: "assets/film-7-original.png", prompt: "Угадай фильм по заблюренному кадру.", answer: "Бойцовский клуб", answerTitle: "Бойцовский клуб", acceptedAnswers: ["бойцовский клуб", "бойцоввский клуб"] },
    ],
  },
  {
    title: "Кайфуй и работай",
    resource: "Остров кайфа",
    cityName: "Кальянная",
    durationMs: 60000,
    manual: true,
    mascotImage: "assets/balloon-cat.png",
    rules:
      "Эстафета на ловкость и скорость. Команды играют по очереди. Команда выстраивается в колонну: первый берёт мяч и передаёт следующему, и так до конца колонны; последний кладёт мяч в корзину. Усложняйте передачу: над головой, между ног или сбоку. Главное — не уронить мяч. За отведённое время 60 секунд команда переносит как можно больше мячей. Побеждает команда, чья корзина полнее.",
    questions: [
      { type: "manual", prompt: "Эстафета с мячами в зале. Баллы начисляет ведущая вручную." },
    ],
  },
  {
    title: "Культурный сервер",
    resource: "Счастье жителей",
    durationMs: 45000,
    questions: [
      { type: "text", prompt: "Какой роман можно назвать главным пользовательским соглашением антиутопии: за вами следят, отказаться нельзя?", answer: "1984 / Джордж Оруэлл" },
      { type: "text", prompt: "Какой фильм превратил “а вдруг мы живём в симуляции?” из философии в массовый поп-культурный кошмар?", answer: "Матрица / The Matrix" },
      { type: "text", prompt: "Кто из литературных героев был бы лучшим data analyst: наблюдает, строит гипотезы, замечает то, что все пропустили?", answer: "Шерлок Холмс / Holmes" },
      { type: "text", prompt: "Кто сказал “You shall not pass!”, то есть провёл самую драматичную модерацию доступа в истории фэнтези?", answer: "Гэндальф / Gandalf" },
      { type: "text", prompt: "Какая фраза из “Маленького принца” звучит как лозунг техподдержки после запуска продукта?", answer: "Мы в ответе за тех, кого приручили" },
      { type: "text", prompt: "Что объединяет карту Мародёров, Google Maps, морские карты и хороший dashboard?", answer: "Навигация / карта / показывают где что находится / помогают ориентироваться" },
      { type: "choice", prompt: "Если бы Кайфоград был приложением, какой у него главный KPI?", options: ["Все счастливы", "Сервер лёг", "Никто не понял правила", "Бюджет исчез"], correct: "A" },
    ],
  },
  {
    title: "Озвучь мем",
    resource: "Театр",
    durationMs: 45000,
    revealAnswers: true,
    questions: [
      { type: "text", image: "assets/mem1.jpeg", prompt: "Озвучь мем по картинке.", answer: "Чипи чипи чапа чапа", acceptedAnswers: ["чипи чипи чапа чапа", "чипичипи чапачапа", "chipi chipi chapa chapa", "dubidubidu"] },
      { type: "text", image: "assets/mem2.jpeg", prompt: "Озвучь мем по картинке.", answer: "Я выживу, я обязательно выживу", acceptedAnswers: ["я выживу я обязательно выживу", "я выживу", "я обязательно выживу"] },
      { type: "text", image: "assets/mem3.jpg", prompt: "Озвучь мем по картинке.", answer: "Если я ношу кандибобер", acceptedAnswers: ["если я ношу кандибобер", "кандибобер"] },
      { type: "text", image: "assets/mem4.jpeg", prompt: "Озвучь мем по картинке.", answer: "Без пяти минут пятого утра", acceptedAnswers: ["без пяти минут пятого утра", "без пяти пять утра", "без 5 минут пятого утра", "без пяти пять"] },
      { type: "text", image: "assets/mem5.jpeg", prompt: "Озвучь мем по картинке.", answer: "Наталья, морская пехота", acceptedAnswers: ["наталья морская пехота", "наталья морская пихота", "морская пехота", "наталья"] },
      { type: "text", image: "assets/mem6.png", prompt: "Озвучь мем по картинке.", answer: "Вы кто такие", acceptedAnswers: ["вы кто такие", "вы кто такие я вас не звал", "я вас не звал"] },
      { type: "text", image: "assets/mem7.png", prompt: "Озвучь мем по картинке.", answer: "ИванГай, хаю хай", acceptedAnswers: ["ивангай хаю хай", "хаю хай", "ивангай"] },
    ],
  },
  {
    title: "Угадай песню",
    resource: "Радио",
    durationMs: 30000,
    revealAnswers: true,
    questions: [
      { type: "song", prompt: "Звучит песня — впишите исполнителя и название.", artist: "Pixies", title: "Where Is My Mind?", artistAccepted: ["pixies", "пиксис"], titleAccepted: ["where is my mind", "where is my mind?"] },
      { type: "song", prompt: "Звучит песня — впишите исполнителя и название.", artist: "Survivor", title: "Eye of the Tiger", artistAccepted: ["survivor", "сурвайвор"], titleAccepted: ["eye of the tiger", "око тигра", "глаз тигра"] },
      { type: "song", prompt: "Звучит песня — впишите исполнителя и название.", artist: "Игорь Корнелюк", title: "Город, которого нет", artistAccepted: ["игорь корнелюк", "корнелюк"], titleAccepted: ["город которого нет"] },
      { type: "song", prompt: "Звучит песня — впишите исполнителя и название.", artist: "Макс Корж", title: "Жить в кайф", artistAccepted: ["макс корж", "корж"], titleAccepted: ["жить в кайф"] },
      { type: "song", prompt: "Звучит песня — впишите исполнителя и название.", artist: "The Prodigy", title: "Breathe", artistAccepted: ["the prodigy", "prodigy", "продиджи"], titleAccepted: ["breathe", "брийз", "бриз"] },
      { type: "song", prompt: "Звучит песня — впишите исполнителя и название.", artist: "Gloria Gaynor", title: "I Will Survive", artistAccepted: ["gloria gaynor", "глория гейнор", "гейнор"], titleAccepted: ["i will survive", "ай вилл сурвайв", "ай вил сурвайв"] },
      { type: "song", prompt: "Звучит песня — впишите исполнителя и название.", artist: "Kylie Minogue", title: "Can't Get You Out Of My Head", artistAccepted: ["kylie minogue", "кайли миноуг", "миноуг", "кайли"], titleAccepted: ["cant get you out of my head", "can't get you out of my head", "кант гет ю аут оф май хед"] },
    ],
  },
  {
    title: "Баг в истории",
    resource: "Музей истории",
    durationMs: 45000,
    questions: [
      { type: "text", prompt: "Какой “подарок от клиента” вошёл в город и стал символом самой известной уязвимости доверия?", answer: "Троянский конь" },
      { type: "text", prompt: "Какой город можно назвать историческим “снэпшотом”, потому что катастрофа законсервировала римскую жизнь?", answer: "Помпеи" },
      { type: "text", prompt: "Как называется исторический баг, когда в фильме про Древний Рим внезапно видны часы, молния или кроссовки?", answer: "Анахронизм" },
      { type: "text", prompt: "Какой корабль стал мемом про самоуверенность системы: “рисков нет, всё предусмотрели”?", answer: "Титаник" },
      { type: "choice", prompt: "Если бы Великая китайская стена была IT-продуктом, что это было бы?", options: ["Firewall", "Docker", "Staffcop", "Стахановец"], correct: "C" },
      { type: "text", prompt: "Какой исторический персонаж был бы идеальным crisis manager релиза: пришёл, увидел, победил?", answer: "Юлий Цезарь / Цезарь" },
      { type: "text", prompt: "Какой “инцидент безопасности” в мифологии начался с того, что нельзя было открывать одну вещь?", answer: "Ящик Пандоры / Пандора" },
    ],
  },
];

export const resourceDescriptions = {
  "Разминка": "Стартовый разогрев перед строительством Кайфограда.",
  "Технологии": "Да. Тут строится техническое сердце города.",
  "Банк": "Финансовый центр Кайфограда.",
  "Территория": "География, места и узнаваемые миры для карты города.",
  "Кинотеатр": "Городской кинотеатр: кадры, которые узнают даже размытыми.",
  "Музей истории": "Память о вашей команде навсегда остаётся в городе.",
  "Театр": "Культурная сцена для жителей — сюда попадают лучшие мемологи.",
  "Радио": "Городское радио: музыка, которую узнают по первым нотам.",
  "Счастье жителей": "По умолчанию все жители города счастливы.",
  "Остров кайфа": "Дымный кальян и право красиво отдыхать.",
};
